title: 我的博客
description: 欢迎来到我的个人博客
url: "https://michael-chen-nju.github.io/"

theme: jekyll-theme-crayon

# 博客作者信息
author:
  name: 陈子昂
  email: 221250121@smail.nju.edu.cn

# 社交链接
social_links:
  github: https://github.com/Michael-Chen-NJU

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag